### ISSUE TITLE
Probably memory leak risk

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-dashboard#31]
In `RootNodeChangeListener`, we create `pathChildrenCache` when `CHILD_ADDED`.Howver,there is no close method invoked when `CHILD_REMOVED`

**Comment by chpengzh** [comment]
`RegistryDataSync.subscribe` may only be invoke **once** while `ContextRefreshEvent` happened,  no more `PathChildrenCache` since then.

You can use method above for simple detection:

- 1. Run `SofaAdminServerApplication` and find pid

- 2. Find all `PathChildrenCache` instance by `jmap`

```
jmap -histo <pid> | grep PathChildrenCache
1327:             4            288  org.apache.curator.framework.recipes.cache.PathChildrenCache
 849:            36            864  org.apache.curator.framework.recipes.cache.PathChildrenCache$9
1074:            20            480  org.apache.curator.framework.recipes.cache.PathChildrenCache$5
1075:            20            480  org.apache.curator.framework.recipes.cache.PathChildrenCacheEvent
1175:            16            384  org.apache.curator.framework.recipes.cache.PathChildrenCache$4
1235:            14            336  org.apache.curator.framework.recipes.cache.PathChildrenCache$6
```

- 3.  Run some rpc providers/consumers

- 4. redo `2`

- 5. Shutdown providers/consumers

- 6. redo `2`

If no more `PathChildrenCache`  is generated, there might be no such memory leak.

**Comment by OrezzerO** [comment]
@chpengzh  Thank you for replay . You are right, `CHILD_ADDED` event can only be triggerd once.
